import time, socket, sys
import random
import uuid
import mysql.connector
######################################################################################################################################
def serverDatabase(pid,cem,rem,msg2tid,ci,ri):
    print("\nStoring PID,Emergency challenge,Emergency response to Server Database....")
    mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="admin",
    database="rfid"
    )
    mycursor = mydb.cursor()
    print("Database connection successful....")
    sql = "Delete from server"
    mycursor.execute(sql)
    mydb.commit()
    for i in range(50):
        sql = "INSERT INTO server (pid,cem,rem) VALUES (%s,%s,%s)"
        x = pid[i]
        y = cem[i]
        z = rem[i]
        val = (x,y,z)
        mycursor.execute(sql, val)
        mydb.commit()
    sql = "INSERT INTO server (pid,cem,rem) VALUES (%s,%s,%s)"
    val = (msg2tid,ci,ri)
    mycursor.execute(sql, val)
    mydb.commit()
    print("Record Inserted")
    
    
######################################################################################################################################
print("\nWelcome to Setup phase of RFID\n")
print("Initialising....\n")
time.sleep(1)

s = socket.socket()
host = socket.gethostname()
ip = socket.gethostbyname(host)
port = 1234
s.bind((host, port))
print(host, "(", ip, ")\n")
name = "Server"
           
s.listen(1)
print("\nWaiting for incoming connections...\n")
conn, addr = s.accept()
print("Received connection from ", addr[0], "(", addr[1], ")\n")

s_name = conn.recv(1024)
s_name = s_name.decode()
print(s_name, "has connected to Socket\n")
conn.send(name.encode())

######################################################################################################################################
#generate Challenge Ci
ci = str(random.randint(99,999999))
conn.send(ci.encode())
ri = conn.recv(1024)
ri = int(ri.decode())
print("Tag has sent response :", ri)
######################################################################################################################################
#Emergency challenge
cem = []
rem = []
for i in range(0,50):
    challenge = str(random.randint(99,999999))
    cem.append(challenge)
    conn.send(challenge.encode())
    response = conn.recv(1024)
    response = int(response.decode())
    rem.append(response)
print("Emergency response generated by Tag =\n",rem)
######################################################################################################################################
#Generate TagID and PID
msg2tid = str(uuid.uuid1().int)
conn.send(msg2tid.encode())
pid = []
for i in range(0,50):
    time.sleep(0.1)
    upid=str(uuid.uuid1().int)
    pid.append(upid)
    conn.send(upid.encode())
#Store id in database file
serverDatabase(pid,cem,rem,msg2tid,ci,ri)
######################################################################################################################################



